### ISSUE TITLE
After the 2020-10-17 dev update some issues returned

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#60]
After the 2020-10-17 dev update some issues returned:
- The echo effect returned #27, this was ok since last week and I wanted to close it.
- The lost carrier issue retrurned #55, I had a train ride with some carrier holes and at the end no sim card present.
   Before the "no sim card" sign, the celular data option could not be switched off.
- The fingerprint recognition stopps at 93% and can only be aborded, but a fingerprint is saved. 
   The unlocking screen do not recognize the fingerprints after a while and only password unlocking is possible.
- The camera app craches sporadic after turning the screen orientation.

**Comment by Xray1870** [comment]
I have also found out ADB was not working anymore, i moved to RC and then it was working again.

**Comment by Stevie00911** [comment]
Do we switch to release candidate version now?
I thought we, as beta testers, test on developer channel.

Ubuntu 16.04. (2020-10-23/2) dev:
- The echo effect is gone again #27
- The lost carrier issue is still present #55
   I lost my carrier while in a call, after that crash "no sim card present".
   Turning power of the phone off for some minutes and reboot: carrier found.
-  The celular data option is not working correctly, switching it on does not connect to the internet.
    After a reboot, celular data option on: connected to the internet.
-  The fingerprint recognition stopps at 93% and can only be aborded, but a fingerprint is saved.
    The unlocking screen does not recognize the fingerprint after a reboot anymore and only password unlocking is possible.
-  The camera app still craches sporadic after turning the screen orientation.
    To get back camera functions a reboot is necessary

**Comment by Xray1870** [comment]
Stevie,

I don't have got my phone from Volla, when i got my phone it was already running RC.

**Comment by wurzer** [comment]
> I lost my carrier while in a call, after that crash "no sim card present".
Turning power of the phone off for some minutes and reboot: carrier found.

Did you move while you have been in a call? Can your reproduce this behaviour?

> The celular data option is not working correctly, switching it on does not connect to the internet.
After a reboot, celular data option on: connected to the internet.

I can't reproduce it. What have you exactly done? Did you start the device with a switched off cellular data option or did switch off and on cellular data option after the device has started?

> The camera app still craches sporadic after turning the screen orientation.
To get back camera functions a reboot is necessary

Did you check, that the camera aspect ratio is the same? If the aspect ration is different, then it is a known issue. See the Wiki article about the epics for our Ubuntu Touch port. We have developer working who is working on the remaining issues camera.

> The fingerprint recognition stopps at 93% and can only be aborded, but a fingerprint is saved.
The unlocking screen does not recognize the fingerprint after a reboot anymore and only password unlocking is possible.

Can you create a new ticket with this issue and a description hos to reproduce this issue. Thanks for your report.

**Comment by TellingBerto** [comment]
Ubuntu 16.04. (2020-10-25/2) dev: 

USB connection from PC to device not working (anymore).

Regression: Issue #12 "MTP does not work"

**Comment by Stevie00911** [comment]
> 
> 
> > I lost my carrier while in a call, after that crash "no sim card present".
> > Turning power of the phone off for some minutes and reboot: carrier found.
> 
> Did you move while you have been in a call? Can your reproduce this behaviour?

No, I did not move while in a call and could not reproduce this behaviour jet.
Additionally I still lost my carrier after flightmode was activated and reactivated.
Only a reboot can help afterwards.
16.04. release candidate (W43)

> 
> > The celular data option is not working correctly, switching it on does not connect to the internet.
> > After a reboot, celular data option on: connected to the internet.
> 
> I can't reproduce it. What have you exactly done? Did you start the device with a switched off cellular data option or did switch off and on cellular data option after the device has started?

The device was in cellular data switched off position and could not be switched on. 
With the release candidate (W43) I have success now.

**Comment by wurzer** [comment]
MTK should work and also the flight mode issue was fixed. We will investigate, which conflicts have caused this problems.

**Comment by Stevie00911** [comment]
With the actual release candidate (W43) the MTK and the flight mode issues are still not fixed.

**Comment by wurzer** [comment]
They have been fixed. It seems a side effect of a some new changes.

**Comment by Stevie00911** [comment]
This is, what I do not understand: why does already fixed features return unfixed into the newer releases?

**Comment by wurzer** [comment]
I assume, it’s an impact respectively side effect of a code change. We need to investigate.

**Comment by TellingBerto** [comment]
Ubuntu 16.04. (2020-W43) Channel: RC

USB connection from PC (openSuse Leap 15.1) to device not working (anymore).
No connection via USB and ADB to device possible.

Regression: Issue #12 "MTP does not work"

**Comment by TellingBerto** [comment]
Ubuntu 16.04. (2020-W44) Channel: RC

USB connection from PC (openSuse Leap 15.1) to device working with MTP.
When phone is connected to PC via USB cable the phone is booting. It does not end up in fastboot mode anymore.

No connection via USB and ADB to device possible.

**Comment by JamiKettunen** [comment]
There was a regression on initramfs level which has now been resolved, and the stuff listed seens to work perfectly fine as of development channel update `2020-10-30/2` and I think a similar patch was also pushed to RC channel.
Please retest this and close the issue/comment back as needed! :)

**Comment by TellingBerto** [comment]
Ubuntu 16.04. (2020-10-31/2) Channel: DEV

Hi JamiKettunen, how are you?

**OK:**
USB connection from PC (openSuse Leap 15.1) to device is working with MTP (files can be copied to/from device).
Connection via USB and ADB to device possible.

**Not OK:**
USB connection to charger: If the phone is switched off and the charger is connected via USB cable, the phone is starting the boot process and ending up in fastboot mode.  #37
When phone is off and connected to PC via USB cable the phone is booting. It is ending up in fastboot mode. #48

**Remarks:** 
- In case the device is ending up in the fastboot mode, the device is not charged. This might be a issue if the battery is fully exhausted.
- The type of cable is not important for this issue (white, black and blue) USB-cables leads to the same result.

Please let us know if you need further input.
Cheers

**Comment by JamiKettunen** [comment]
@TellingBerto that is a different problem unrelated to this issue, I've actually sent [a fix for this upstream](https://github.com/Halium/initramfs-tools-halium/pull/22) and it's waiting to be merged. I'll go ahead and close this issue.

If any issue from here still isn't resolved after updating, comment on existing / create a new issue as needed! :)
